package com.epam.testorm.greenDao.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.epam.testorm.greenDao.model.NewsDao;
import com.epam.testorm.greenDao.model.AuthorDao;
import com.epam.testorm.greenDao.model.ContentDao;
import com.epam.testorm.greenDao.model.ImagesDao;
import com.epam.testorm.greenDao.model.LinksDao;
import com.epam.testorm.greenDao.model.VideosDao;
import com.epam.testorm.greenDao.model.AudiosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        NewsDao.createTable(db, ifNotExists);
        AuthorDao.createTable(db, ifNotExists);
        ContentDao.createTable(db, ifNotExists);
        ImagesDao.createTable(db, ifNotExists);
        LinksDao.createTable(db, ifNotExists);
        VideosDao.createTable(db, ifNotExists);
        AudiosDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        NewsDao.dropTable(db, ifExists);
        AuthorDao.dropTable(db, ifExists);
        ContentDao.dropTable(db, ifExists);
        ImagesDao.dropTable(db, ifExists);
        LinksDao.dropTable(db, ifExists);
        VideosDao.dropTable(db, ifExists);
        AudiosDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(NewsDao.class);
        registerDaoClass(AuthorDao.class);
        registerDaoClass(ContentDao.class);
        registerDaoClass(ImagesDao.class);
        registerDaoClass(LinksDao.class);
        registerDaoClass(VideosDao.class);
        registerDaoClass(AudiosDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
