package com.epam.testorm.greenDao.model;

import com.epam.testorm.greenDao.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS".
 */
public class News {

    private Long id;
    private String url;
    private Long timestamp;
    private Long authorId;
    private Long contentId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient NewsDao myDao;

    private Author author;
    private Long author__resolvedKey;

    private Content content;
    private Long content__resolvedKey;


    public News() {
    }

    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String url, Long timestamp, Long authorId, Long contentId) {
        this.id = id;
        this.url = url;
        this.timestamp = timestamp;
        this.authorId = authorId;
        this.contentId = contentId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getNewsDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Long getAuthorId() {
        return authorId;
    }

    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    public Long getContentId() {
        return contentId;
    }

    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /** To-one relationship, resolved on first access. */
    public Author getAuthor() {
        Long __key = this.authorId;
        if (author__resolvedKey == null || !author__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AuthorDao targetDao = daoSession.getAuthorDao();
            Author authorNew = targetDao.load(__key);
            synchronized (this) {
                author = authorNew;
            	author__resolvedKey = __key;
            }
        }
        return author;
    }

    public void setAuthor(Author author) {
        synchronized (this) {
            this.author = author;
            authorId = author == null ? null : author.getId();
            author__resolvedKey = authorId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Content getContent() {
        Long __key = this.contentId;
        if (content__resolvedKey == null || !content__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ContentDao targetDao = daoSession.getContentDao();
            Content contentNew = targetDao.load(__key);
            synchronized (this) {
                content = contentNew;
            	content__resolvedKey = __key;
            }
        }
        return content;
    }

    public void setContent(Content content) {
        synchronized (this) {
            this.content = content;
            contentId = content == null ? null : content.getId();
            content__resolvedKey = contentId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
